# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_recv_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField()),
                ('status', models.IntegerField(choices=[(1, '正在跟单'), (1, '已成单'), (1, '3天未跟进'), (1, '15天未成单')], default=1, verbose_name='状态')),
                ('memo', models.CharField(max_length=255, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='crm.Customer', verbose_name='客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='crm.UserInfo', verbose_name='课程顾问')),
            ],
        ),
    ]
